// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bakaryshop.Data;

namespace bakaryshop.Data.Migrations
{
    [DbContext(typeof(BakeryShopContext))]
    partial class BakeryShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("bakaryshop.Model.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagename")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.Property<string>("product_name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "carrot cake any description",
                            imagename = "carrot-cake-1200x800",
                            price = 0m,
                            product_name = "carrot cake"
                        },
                        new
                        {
                            id = 2,
                            description = "cup cake any description",
                            imagename = "cup cake.jpg",
                            price = 0m,
                            product_name = "cup cake"
                        },
                        new
                        {
                            id = 3,
                            description = "choclate cake any description",
                            imagename = "choclate cake.jpg",
                            price = 0m,
                            product_name = "choclate cake"
                        },
                        new
                        {
                            id = 4,
                            description = "Lemon-cake any description",
                            imagename = "Lemon-cake.jpg",
                            price = 0m,
                            product_name = "Lemon-cake"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
